Fix doctypes

diff --git a/scripts/doctypes b/scripts/doctypes
--- a/scripts/doctypes
+++ b/scripts/doctypes
@@ -2,31 +2,29 @@
 
 function gitfiles() {
     root=$(git rev-parse --show-toplevel 2> /dev/null)
-    if [ -z "$root" ]; then
-        exit 1
-    fi
-    if [ "$1" == "." ]; then
-        # FIXME: limit to the paths below pwd
-        # echo "Processing all files in repository"
-        paths=$(git ls-files | grep "\.py$" | awk -v root="$root" '{print root"/"$1}')
-    else
-        # echo "Processing modified in repository"
-        paths=$({ git diff --name-only ; git diff --name-only --staged ; } | sort | uniq | grep "\.py$" | awk -v root="$root" '{print root"/"$1}')
+    if [ ! -z "$root" ]; then
+        if [ "$1" == "." ]; then
+            # FIXME: limit to the paths below pwd
+            # echo "Processing all files in repository"
+            paths=$(git ls-files | grep "\.py$" | awk -v root="$root" '{print root"/"$1}')
+        else
+            # echo "Processing modified in repository"
+            paths=$({ git diff --name-only ; git diff --name-only --staged ; } | sort | uniq | grep "\.py$" | awk -v root="$root" '{print root"/"$1}')
+        fi
     fi
 }
 
 function hgfiles() {
     root=$(hg root 2> /dev/null)
-    if [ -z "$root" ]; then
-        exit 1
-    fi
-    if [ "$1" == "." ]; then
-        # FIXME: limit to the paths below pwd
-        # echo "Processing all files in repository"
-        paths=$(hg manifest | grep "\.py$" | awk -v root="$root" '{print root"/"$1}')
-    else
-        # echo "Processing modified in repository"
-        paths=$(hg status -m -a -n | grep "\.py$" | awk -v root="$root" '{print root"/"$1}')
+    if [ ! -z "$root" ]; then
+        if [ "$1" == "." ]; then
+            # FIXME: limit to the paths below pwd
+            # echo "Processing all files in repository"
+            paths=$(hg manifest | grep "\.py$" | awk -v root="$root" '{print root"/"$1}')
+        else
+            # echo "Processing modified in repository"
+            paths=$(hg status -m -a -n | grep "\.py$" | awk -v root="$root" '{print root"/"$1}')
+        fi
     fi
 }
 
@@ -35,10 +33,10 @@ function doctypes() {
     if [[ -z "$1" || "$1" == "." ]]; then
         # no paths given. find modified files in the current repo
         gitfiles $1
-        if [ $? -ne 0 ]; then
+        if [ -z $root ]; then
             hgfiles $1
-            if [ $? -ne 0 ]; then
-                echo "Error: could not find .git or .hg directory"
+            if [ -z $root ]; then
+                echo "Error: could not find .git or .hg directory" >&2
                 exit 1
             fi
         fi
@@ -48,7 +46,7 @@ function doctypes() {
         root=`pwd`
     fi
     cd $root
-    echo "Converting docstrings to type comments"
+    echo "Converting docstrings to type comments" >&2
     doc484 --write $paths
 }
 
